# Generated by Django 4.2 on 2024-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('R', 'Reptil'), ('P', 'Planta'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego'), ('E', 'Eléctrica')], max_length=30),
        ),
    ]
