# Generated by Django 4.2 on 2024-07-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('A', 'Agua'), ('P', 'Planta'), ('F', 'Fuego'), ('R', 'Reptil'), ('T', 'Tierra')], max_length=30),
        ),
    ]
