# Generated by Django 4.2 on 2024-08-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0012_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('P', 'Planta'), ('T', 'Tierra'), ('F', 'Fuego'), ('A', 'Agua'), ('R', 'Reptil')], max_length=30),
        ),
    ]
