# Generated by Django 4.2 on 2024-08-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0013_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(default='trainer_images/default.png', upload_to='trainer_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('R', 'Reptil'), ('A', 'Agua'), ('T', 'Tierra'), ('E', 'Eléctrico'), ('P', 'Planta')], max_length=30),
        ),
    ]
