# Generated by Django 4.2 on 2024-08-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0014_trainer_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('R', 'Reptil'), ('F', 'Fuego'), ('A', 'Agua'), ('T', 'Tierra'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
